#!/usr/bin/env bash
#
# Regenerates docs/CODEMAP.md from each module's README.md (Tech Spec §9.4).
# Run this whenever a module is added/removed under apps/api/app/Modules/.
# Doesn't touch apps/web — it has no per-module READMEs yet (Stage 0 only
# defines route groups, not an internal module structure for the frontend).

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
MODULES_DIR="$ROOT_DIR/apps/api/app/Modules"
OUT_FILE="$ROOT_DIR/docs/CODEMAP.md"

{
  echo "# CODEMAP"
  echo
  echo "Auto-generated by \`infra/scripts/generate-codemap.sh\` from each"
  echo "module's \`README.md\` — do not hand-edit, re-run the script instead."
  echo
  echo "## apps/api/app/Modules"
  echo

  found_module=false
  if [ -d "$MODULES_DIR" ]; then
    for module_dir in "$MODULES_DIR"/*/; do
      [ -d "$module_dir" ] || continue
      module_name="$(basename "$module_dir")"
      readme="$module_dir/README.md"

      found_module=true
      echo "### $module_name"
      echo

      if [ -f "$readme" ]; then
        # First non-empty, non-heading line as the one-line summary.
        summary="$(grep -v '^#' "$readme" | grep -v '^\s*$' | head -n 1 || true)"
        echo "${summary:-_(no summary in README.md)_}"
      else
        echo "_(no README.md yet)_"
      fi
      echo
    done
  fi

  if [ "$found_module" = false ]; then
    echo "No modules yet — Tahap 1 adds the first ones (\`Tenant\`, \`Auth\`)."
    echo "See \`apps/api/app/Modules/README.md\` for the planned list and the"
    echo "module-boundary rule this file will start tracking once modules exist."
    echo
  fi
} > "$OUT_FILE"

echo "Written to $OUT_FILE"
